import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import styles from "./EyeHistory.module.css";
import { useAuth } from "../../context/authContext";
import Sidebar from "../../components/Sidebar";
import eyeBg from "../../assets/eyebg2.jpg"; // optional: adjust image path

const EyeHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const { patientId, token } = useAuth();

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const res = await axios.get(`/api/users/eye/history/${patientId}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setHistory(Array.isArray(res.data.history) ? res.data.history : []);
      } catch (err) {
        console.error(err);
        setError("Eye health history not found.");
      } finally {
        setLoading(false);
      }
    };

    if (patientId) fetchHistory();
  }, [patientId]);

  const eyeMenu = [
    { label: "Prediction", path: "/eye" },
    { label: "Prediction History", path: "/eye/history" },
    { label: "Progress Status", path: "/eye/progress" },
  ];

  const exportToPDF = () => {
    const doc = new jsPDF();
    const userInfo = JSON.parse(localStorage.getItem("user-info"));
    const userName = userInfo?.name || "Patient";
    const email = userInfo?.email || "N/A";

    doc.setFontSize(20);
    doc.setTextColor(100, 100, 180);
    doc.setFont("helvetica", "bold");
    doc.text("👁️ PraanCare Eye - Health History Report", 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(33, 33, 33);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${userName}`, 14, 30);
    doc.text(`Email: ${email}`, 14, 36);
    doc.text(`Patient ID: ${patientId || "Unknown"}`, 14, 42);

    const tableColumn = [
      "Date",
      "Sleep (hrs)",
      "Quality",
      "Stress",
      "Heart Rate",
      "Steps",
      "Screen Time",
      "Eye Strain",
      "Redness",
      "Irritation",
      "Prediction",
      "Confidence",
    ];

    const tableRows = history.map((entry) => [
      new Date(entry.createdAt).toLocaleDateString(),
      entry.sleepDuration,
      entry.qualityOfSleep,
      entry.stressLevel,
      entry.heartRate,
      entry.dailySteps,
      entry.screenTime,
      entry.eyeStrain,
      entry.eyeRedness,
      entry.eyeIrritation,
      entry.prediction,
      `${entry.probability?.toFixed(2)}%`,
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 50,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [100, 100, 180], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    const finalY = doc.lastAutoTable.finalY || 80;
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text("“Your eyes show the strength of your soul.” – Paulo Coelho", 14, finalY + 10);
    doc.text(
      "This report was generated by PraanCare – holistic health for your eyes too!",
      14,
      finalY + 18
    );

    doc.save(`PraanCare_Eye_Report_${userName}.pdf`);
  };

  const clearHistory = async () => {
    const confirmClear = window.confirm("Are you sure you want to delete your eye history?");
    if (!confirmClear) return;

    try {
      await axios.delete(`/api/users/eye/history/${patientId}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
      setHistory([]);
      alert("✅ Eye history cleared!");
    } catch (err) {
      console.error(err);
      alert("❌ Failed to clear eye history.");
    }
  };

  return (
    <div className={styles.eyeHistoryContainer}>
      <div className={styles.bgOverlay} style={{ backgroundImage: `url(${eyeBg})` }}></div>
      <Sidebar menuItems={eyeMenu} className="sidebar-permanent sidebar-eye" />

      <h2 className={styles.title}>👁️ Eye Health History</h2>

      {loading ? (
        <p className={styles.status}>Loading...</p>
      ) : error ? (
        <p className={styles.error}>{error}</p>
      ) : history.length === 0 ? (
        <p className={styles.status}>No records found.</p>
      ) : (
        <>
          <div className={styles.actionButtons}>
            <button onClick={exportToPDF} className={styles.btnExport}>
              📄 Export to PDF
            </button>
            <button onClick={clearHistory} className={styles.btnClear}>
              🗑️ Clear History
            </button>
          </div>

          <table className={styles.historyTable}>
            <thead>
              <tr>
                <th>Date</th>
                <th>Sleep (hrs)</th>
                <th>Quality</th>
                <th>Stress</th>
                <th>Heart Rate</th>
                <th>Steps</th>
                <th>Screen Time</th>
                <th>Eye Strain</th>
                <th>Redness</th>
                <th>Irritation</th>
                <th>Prediction</th>
                <th>Confidence</th>
              </tr>
            </thead>
            <tbody>
              {history.map((entry) => (
                <tr key={entry._id}>
                  <td>{new Date(entry.createdAt).toLocaleDateString()}</td>
                  <td>{entry.sleepDuration}</td>
                  <td>{entry.qualityOfSleep}</td>
                  <td>{entry.stressLevel}</td>
                  <td>{entry.heartRate}</td>
                  <td>{entry.dailySteps}</td>
                  <td>{entry.screenTime}</td>
                  <td>{entry.eyeStrain}</td>
                  <td>{entry.eyeRedness}</td>
                  <td>{entry.eyeIrritation}</td>
                  <td>{entry.prediction}</td>
                  <td>{entry.probability?.toFixed(2)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
};

export default EyeHistory;
