import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import styles from "./CardiacHistory.module.css";
import { useAuth } from "../../context/authContext";
import Sidebar from "../../components/Sidebar";
import cardiacBg from "../../assets/cardiacbg4.jpg";

const CardiacHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const { patientId, token } = useAuth();

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const res = await axios.get(`/api/users/cardiac/history/${patientId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        setHistory(Array.isArray(res.data.history) ? res.data.history : []);
      } catch (err) {
        console.error(err);
        setError("Cardiac health history not found.");
      } finally {
        setLoading(false);
      }
    };

    if (patientId) fetchHistory();
  }, [patientId]);

  const cardiacMenu = [
    { label: "Prediction", path: "/cardiac" },
    { label: "Prediction History", path: "/cardiac/history" },
    { label: "Progress Status", path: "/cardiac/progress" },
  ];

  const reverseMappings = {
    chestPainType: ["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"],
    fastingBloodSugar: ["No", "Yes"],
    restingECG: ["Normal", "ST-T Wave Abnormality", "Left Ventricular Hypertrophy"],
    exerciseAngina: ["No", "Yes"],
    stSlope: ["Upsloping", "Flat", "Downsloping"],
  };
  const tableColumn = [
  "Date",
  "Chest Pain",
  "Resting BP",
  "Cholesterol",
  "FBS",
  "ECG",
  "Max HR",
  "Angina",
  "Oldpeak",
  "ST Slope",
  "Prediction",
  "Confidence",
];


  const exportToPDF = () => {
    const doc = new jsPDF();
    const userInfo = JSON.parse(localStorage.getItem("user-info"));
    const userName = userInfo?.name || "Patient";
    const email = userInfo?.email || "N/A";

    doc.setFontSize(20);
    doc.setTextColor(180, 60, 60);
    doc.setFont("helvetica", "bold");
    doc.text("🫀 PraanCare Cardiac - Health History Report", 14, 20);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(`Name: ${userName}`, 14, 30);
    doc.text(`Email: ${email}`, 14, 36);
    doc.text(`Patient ID: ${patientId || "Unknown"}`, 14, 42);

    const tableRows = history.map((entry) => [
      new Date(entry.createdAt).toLocaleDateString(),
      reverseMappings.chestPainType[entry.chestPainType],
      entry.restingBP,
      entry.cholesterol,
      reverseMappings.fastingBloodSugar[entry.fastingBloodSugar],
      reverseMappings.restingECG[entry.restingECG],
      entry.maxHeartRate,
      reverseMappings.exerciseAngina[entry.exerciseAngina],
      entry.oldpeak,
      reverseMappings.stSlope[entry.stSlope],
      entry.prediction,
      `${entry.probability?.toFixed(2)}%`,
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 50,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [180, 60, 60], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    const finalY = doc.lastAutoTable.finalY || 80;
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text("“The heart is the engine of life. Keep it strong.”", 14, finalY + 10);
    doc.text("This report was generated by PraanCare – love your heart!", 14, finalY + 18);

    doc.save(`PraanCare_Cardiac_Report_${userName}.pdf`);
  };

  const clearHistory = async () => {
    if (!window.confirm("Are you sure you want to delete your cardiac history?")) return;

    try {
      await axios.delete(`/api/users/cardiac/history/${patientId}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setHistory([]);
      alert("✅ Cardiac history cleared!");
    } catch (err) {
      console.error(err);
      alert("❌ Failed to clear cardiac history.");
    }
  };

  return (
    <div className={styles.cardiacHistoryContainer}>
      <div className={styles.bgOverlay} style={{ backgroundImage: `url(${cardiacBg})` }}></div>
      <Sidebar menuItems={cardiacMenu} className="sidebar-permanent sidebar-cardiac" />

      <h2 className={styles.title}>🫀 Cardiac Health History</h2>

      {loading ? (
        <p className={styles.status}>Loading...</p>
      ) : error ? (
        <p className={styles.error}>{error}</p>
      ) : history.length === 0 ? (
        <p className={styles.status}>No records found.</p>
      ) : (
        <>
          <div className={styles.actionButtons}>
            <button onClick={exportToPDF} className={styles.btnExport}>📄 Export to PDF</button>
            <button onClick={clearHistory} className={styles.btnClear}>🗑️ Clear History</button>
          </div>

          <table className={styles.historyTable}>
            <thead>
              <tr>
                {tableColumn.map((col) => (<th key={col}>{col}</th>))}
              </tr>
            </thead>
            <tbody>
              {history.map((entry) => (
                <tr key={entry._id}>
                  <td>{new Date(entry.createdAt).toLocaleDateString()}</td>
                  <td>{reverseMappings.chestPainType[entry.chestPainType]}</td>
                  <td>{entry.restingBP}</td>
                  <td>{entry.cholesterol}</td>
                  <td>{reverseMappings.fastingBloodSugar[entry.fastingBloodSugar]}</td>
                  <td>{reverseMappings.restingECG[entry.restingECG]}</td>
                  <td>{entry.maxHeartRate}</td>
                  <td>{reverseMappings.exerciseAngina[entry.exerciseAngina]}</td>
                  <td>{entry.oldpeak}</td>
                  <td>{reverseMappings.stSlope[entry.stSlope]}</td>
                  <td>{entry.prediction}</td>
                  <td>{entry.probability?.toFixed(2)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
};

export default CardiacHistory;
