import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; // ✅ use named import
import styles from "./SleepHistory.module.css";
import { useAuth } from "../../context/authContext";
import Sidebar from "../../components/Sidebar";
import sleepBg from "../../assets/sleepbg3.jpg";


const SleepHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const { patientId, token } = useAuth();

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const res = await axios.get(`/api/users/sleep/history/${patientId}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setHistory(Array.isArray(res.data.history) ? res.data.history : []);
      } catch (err) {
        console.error(err);
        setError("Sleep history not found.");
      } finally {
        setLoading(false);
      }
    };

    if (patientId) fetchHistory();
  }, [patientId]);

  const sleepMenu = [
    { label: "Prediction", path: "/sleep" },
    { label: "Prediction History", path: "/sleep/predictionHistory" },
    { label: "Progress Status", path: "/sleep/progress" },
  ];

  const exportToPDF = () => {
    const doc = new jsPDF();
    const userInfo = JSON.parse(localStorage.getItem("user-info"));
    const userName = userInfo?.name || "Patient";
    const email = userInfo?.email || "N/A";
    const id = patientId || "Unknown";

    // 🟣 Title - PraanCare
    doc.setFontSize(20);
    doc.setTextColor(56, 108, 179); // bluish purple
    doc.setFont("helvetica", "bold");
    doc.text("🩺 PraanCare Sleep Report", 14, 20);

    // 🟢 Patient Info
    doc.setFontSize(11);
    doc.setTextColor(33, 33, 33);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${userName}`, 14, 30);
    doc.text(`Email: ${email}`, 14, 36);
    doc.text(`Patient ID: ${id}`, 14, 42);

    // 📊 Table
    const tableColumn = [
      "Date",
      "Sleep (hrs)",
      "Quality",
      "Stress",
      "Heart Rate",
      "BMI Category",
      "Prediction",
    ];
    const bmiLabels = ["Underweight", "Normal", "Overweight", "Obese"];
    const stressLabels = [
      "Mild",
      "Normal",
      "Moderate",
      "Severe",
      "Extremely severe",
    ];

    const tableRows = history.map((entry) => {
      const bmiText =
        typeof entry.bmiCategory === "number"
          ? bmiLabels[entry.bmiCategory]
          : entry.bmiCategory;
      const stressText =
        typeof entry.stressLevel === "number"
          ? stressLabels[entry.stressLevel - 1]
          : entry.stressLevel;
      return [
        new Date(entry.createdAt).toLocaleDateString(),
        entry.sleepDuration,
        entry.qualityOfSleep,
        stressText,
        entry.heartRate,
        bmiText,
        entry.prediction,
      ];
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 50,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [56, 108, 179], textColor: 255 },
      alternateRowStyles: { fillColor: [240, 240, 240] },
    });

    // 🌈 Ending Note
    const finalY = doc.lastAutoTable.finalY || 80;
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text("“Sleep is the best meditation.” – Dalai Lama", 14, finalY + 10);
    doc.text(
      "This report was generated by PraanCare – your holistic health companion.",
      14,
      finalY + 18
    );

    // 🖼️ Optional Image (bottom right corner)
    // You can add a wellness logo or image in base64 format here
    // Example: doc.addImage(base64String, 'JPEG', x, y, width, height);
    // For now, you can add a placeholder or leave it

    doc.save(`PraanCare_Sleep_Report_${userName}.pdf`);
  };

  const clearHistory = async () => {
    const confirmClear = window.confirm(
      "Are you sure you want to delete your sleep history?"
    );
    if (!confirmClear) return;

    try {
      await axios.delete(`/api/users/sleep/history/${patientId}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
      setHistory([]);
      alert("✅ Sleep history cleared!");
    } catch (err) {
      console.error(err);
      alert("❌ Failed to clear sleep history.");
    }
  };

  return (
    <div className={styles.sleepHistoryContainer}>
      <div
        className={styles.bgOverlay}
        style={{ backgroundImage: `url(${sleepBg})` }}
      ></div>
      <Sidebar
        menuItems={sleepMenu}
        className="sidebar-permanent sidebar-sleep"
      />

      <h2 className={styles.title}>🕒 Sleep History</h2>

      {loading ? (
        <p className={styles.status}>Loading...</p>
      ) : error ? (
        <p className={styles.error}>{error}</p>
      ) : history.length === 0 ? (
        <p className={styles.status}>No records found.</p>
      ) : (
        <>
          <div className={styles.actionButtons}>
            <button onClick={exportToPDF} className={styles.btnExport}>
              📄 Export to PDF
            </button>
            <button onClick={clearHistory} className={styles.btnClear}>
              🗑️ Clear History
            </button>
          </div>

          <table className={styles.historyTable}>
            <thead>
              <tr>
                <th>Date</th>
                <th>Sleep (hrs)</th>
                <th>Quality</th>
                <th>Stress</th>
                <th>Heart Rate</th>
                <th>BMI Category</th>
                <th>Prediction</th>
              </tr>
            </thead>
            <tbody>
              {history.map((entry) => {
                const bmiLabels = [
                  "Underweight",
                  "Normal",
                  "Overweight",
                  "Obese",
                ];
                const stressLabels = [
                  "Mild",
                  "Normal",
                  "Moderate",
                  "Severe",
                  "Extremely severe",
                ];
                const bmiText =
                  typeof entry.bmiCategory === "number"
                    ? bmiLabels[entry.bmiCategory]
                    : entry.bmiCategory;
                const stressText =
                  typeof entry.stressLevel === "number"
                    ? stressLabels[entry.stressLevel - 1]
                    : entry.stressLevel;

                return (
                  <tr key={entry._id}>
                    <td>{new Date(entry.createdAt).toLocaleDateString()}</td>
                    <td>{entry.sleepDuration}</td>
                    <td>{entry.qualityOfSleep}</td>
                    <td>{stressText}</td>
                    <td>{entry.heartRate}</td>
                    <td>{bmiText}</td>
                    <td>{entry.prediction}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
};

export default SleepHistory;
